# This project uses the GitFlow Workflow as defined here:
#   https://www.atlassian.com/git/tutorials/comparing-workflows#GitFlow-workflow
image: hspconsortium/hspc-ubuntu-base
clone:           # the 'clone' section
  depth: 1       # the depth, in this case the clone will contain last one commits

pipelines:
  default:
    - step:
        script:
          - echo "Please use a GitFlow branch"
          - exit 1;
  branches:
    develop:
      - step:
          script:
            - . ci-0-set-properties.sh
            - . ci-1-prepare-sources.sh
            - . ci-2-docker-image.sh
            - . ci-3-aws-update.sh
#    feature/*:
#      - step:
#          caches:
#            - node
#          script:
#            - npm install
#    release/*:
#      - step:
#          caches:
#            - node
#          script:
#            - npm install
#    hotfix/*:
#      - step:
#          caches:
#            - node
#          script:
#            - npm install
#    master:
#      - step:
#          caches:
#            - node
#          script:
#            - . ci-0-set-properties.sh
#            - . ci-1-prepare-sources.sh
#            - . ci-2-docker-image.sh
#            - . ci-3-aws-update.sh
options:
  docker: true