# This project uses the GitFlow Workflow as defined here:
#   https://www.atlassian.com/git/tutorials/comparing-workflows#GitFlow-workflow
image: node:8.7.0
clone:           # the 'clone' section
  depth: 1       # the depth, in this case the clone will contain last one commits

pipelines:
  default:
    - step:
        script:
          - echo "Please use a GitFlow branch"
          - exit 1;
  branches:
    develop:
      - step:
          script:
            - export ACTIVE_ENV=test
            - export TARGET_AWS_CLUSTER=hspc-test
            - export TARGET_AWS_SERVICE=react-sandbox-manager-testservice
            - . ci-0-set-properties.sh
            - . ci-1-prepare-sources.sh
            - . ci-2-docker-image.sh
            - . ci-3-aws-update.sh react-sandbox-manager
    feature/*:
      - step:
          caches:
            - node
          script:
            - npm install
    release/*:
      - step:
          caches:
            - node
          script:
            - npm install
    hotfix/*:
      - step:
          caches:
            - node
          script:
            - npm install
    master:
      - step:
          caches:
            - node
          script:
            - export ACTIVE_ENV=prod
            - . ci-0-set-properties.sh
            - . ci-1-prepare-sources.sh
            - . ci-2-docker-image.sh
            - . ci-3-aws-update.sh react-sandbox-manager
options:
  docker: true
