set PASSWORD=test
set SANDBOX_NAME=loadtest0 && set USERNAME=testuser1 && start /b npm run test --silent &
set SANDBOX_NAME=loadtest1 && set USERNAME=testuser10 && start /b npm run test --silent &
set SANDBOX_NAME=loadtest2 && set USERNAME=testuser100 && start /b npm run test --silent &
set SANDBOX_NAME=loadtest3 && set USERNAME=testuser11 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest4 && set USERNAME=testuser12 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest5 && set USERNAME=testuser13 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest6 && set USERNAME=testuser14 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest7 && set USERNAME=testuser15 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest8 && set USERNAME=testuser16 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest9 && set USERNAME=testuser17 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest10 && set USERNAME=testuser18 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest11 && set USERNAME=testuser19 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest12 && set USERNAME=testuser2 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest13 && set USERNAME=testuser20 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest14 && set USERNAME=testuser21 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest15 && set USERNAME=testuser22 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest16 && set USERNAME=testuser23 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest17 && set USERNAME=testuser24 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest18 && set USERNAME=testuser25 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest19 && set USERNAME=testuser26 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest20 && set USERNAME=testuser27 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest21 && set USERNAME=testuser28 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest22 && set USERNAME=testuser29 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest23 && set USERNAME=testuser3 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest24 && set USERNAME=testuser30 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest25 && set USERNAME=testuser31 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest26 && set USERNAME=testuser32 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest27 && set USERNAME=testuser33 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest28 && set USERNAME=testuser34 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest29 && set USERNAME=testuser35 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest30 && set USERNAME=testuser36 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest31 && set USERNAME=testuser37 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest32 && set USERNAME=testuser38 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest33 && set USERNAME=testuser39 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest34 && set USERNAME=testuser4 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest35 && set USERNAME=testuser40 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest36 && set USERNAME=testuser41 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest37 && set USERNAME=testuser42 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest38 && set USERNAME=testuser43 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest39 && set USERNAME=testuser44 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest40 && set USERNAME=testuser45 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest41 && set USERNAME=testuser46 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest42 && set USERNAME=testuser47 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest43 && set USERNAME=testuser48 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest44 && set USERNAME=testuser49 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest45 && set USERNAME=testuser5 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest46 && set USERNAME=testuser50 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest47 && set USERNAME=testuser51 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest48 && set USERNAME=testuser52 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest49 && set USERNAME=testuser53 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest50 && set USERNAME=testuser54 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest51 && set USERNAME=testuser55 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest52 && set USERNAME=testuser56 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest53 && set USERNAME=testuser57 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest54 && set USERNAME=testuser58 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest55 && set USERNAME=testuser59 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest56 && set USERNAME=testuser6 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest57 && set USERNAME=testuser60 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest58 && set USERNAME=testuser61 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest59 && set USERNAME=testuser62 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest60 && set USERNAME=testuser63 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest61 && set USERNAME=testuser64 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest62 && set USERNAME=testuser65 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest63 && set USERNAME=testuser66 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest64 && set USERNAME=testuser67 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest65 && set USERNAME=testuser68 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest66 && set USERNAME=testuser69 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest67 && set USERNAME=testuser7 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest68 && set USERNAME=testuser70 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest69 && set USERNAME=testuser71 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest70 && set USERNAME=testuser72 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest71 && set USERNAME=testuser73 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest72 && set USERNAME=testuser74 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest73 && set USERNAME=testuser75 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest74 && set USERNAME=testuser76 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest75 && set USERNAME=testuser77 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest76 && set USERNAME=testuser78 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest77 && set USERNAME=testuser79 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest78 && set USERNAME=testuser8 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest79 && set USERNAME=testuser80 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest80 && set USERNAME=testuser81 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest81 && set USERNAME=testuser82 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest82 && set USERNAME=testuser83 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest83 && set USERNAME=testuser84 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest84 && set USERNAME=testuser85 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest85 && set USERNAME=testuser86 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest86 && set USERNAME=testuser87 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest87 && set USERNAME=testuser88 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest88 && set USERNAME=testuser89 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest89 && set USERNAME=testuser9 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest90 && set USERNAME=testuser90 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest91 && set USERNAME=testuser91 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest92 && set USERNAME=testuser92 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest93 && set USERNAME=testuser93 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest94 && set USERNAME=testuser94 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest95 && set USERNAME=testuser95 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest96 && set USERNAME=testuser96 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest97 && set USERNAME=testuser97 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest98 && set USERNAME=testuser98 && start /b npm run test --silent &
@REM set SANDBOX_NAME=loadtest99 && set USERNAME=testuser99 && start /b npm run test --silent &
